spring:
  application:
    name: app
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
